apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/mejrioussama/supportflow-backend:sha-15cdb6439a94d3f36fd2448f65e71c8b0b53bf43
