apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/mejrioussama/supportflow-backend:sha-9b6a4fa31608b6c46627388256c92db3a016dadf
