apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/mejrioussama/supportflow-backend:sha-f473d90ef1cfc49741e62cb598e23bee726dc101
