apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-frontend
  namespace: supportflow
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mejrioussama/supportflow-frontend:sha-5407f93bfc0b7f747097ccae506278273936c08d
