apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mejrioussama/supportflow-frontend:sha-f37682c5dc6a6d6621f62da49324783a55f95266
