apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mejrioussama/supportflow-frontend:sha-23aef3443d8f655a74b4b1fed25b0819540abc1e
