apiVersion: v1
kind: ConfigMap
metadata:
  name: supportflow-config
  namespace: supportflow
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://supportflow-mysql:3306/supportflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: supportflow
  SPRING_DATASOURCE_PASSWORD: supportflow123
  KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/supportflow
  KEYCLOAK_JWK_URI: http://host.docker.internal:8180/realms/supportflow/protocol/openid-connect/certs
  KEYCLOAK_ADMIN_URL: http://host.docker.internal:8180
  SUPPORTFLOW_SECURITY_PORTAL_URL: http://host.docker.internal:8180/realms/supportflow/account
  ALFRESCO_URL: http://host.docker.internal:8090/alfresco/api/-default-/public/cmis/versions/1.1/atom
  AI_AGENT_URL: http://host.docker.internal:8000
