apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-frontend
  namespace: supportflow
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: support-flow-frontend:latest
          imagePullPolicy: Never
