apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supportflow
resources:
  - ../../base
patches:
  - path: configmap-patch.yaml
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
