-- SupportFlow application schema before workflow synchronization jobs.
-- Existing installations are baselined at version 1 and do not execute this file.

CREATE TABLE clients (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    code VARCHAR(20) NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(255),
    city VARCHAR(50),
    country VARCHAR(50),
    postal_code VARCHAR(10),
    industry VARCHAR(50),
    contract_type VARCHAR(50),
    sla_level VARCHAR(20),
    is_active BIT,
    logo_url VARCHAR(255),
    notes TEXT,
    PRIMARY KEY (id),
    CONSTRAINT uk_clients_code UNIQUE (code),
    INDEX idx_client_code (code),
    INDEX idx_client_name (company_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE support_categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    code VARCHAR(50) NOT NULL,
    label VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active BIT NOT NULL,
    sort_order INT,
    PRIMARY KEY (id),
    CONSTRAINT uk_support_categories_code UNIQUE (code),
    INDEX idx_support_category_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    avatar_url VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    keycloak_id VARCHAR(255),
    is_active BIT,
    last_login DATETIME(6),
    client_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_keycloak_id UNIQUE (keycloak_id),
    CONSTRAINT fk_users_client FOREIGN KEY (client_id) REFERENCES clients (id),
    INDEX idx_user_email (email),
    INDEX idx_user_keycloak (keycloak_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tickets (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    reference VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    impact VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    score INT,
    sla_hours INT,
    sla_deadline DATETIME(6),
    sla_breached BIT,
    sla_warning_sent BIT,
    sla_phase VARCHAR(30),
    escalated_at DATETIME(6),
    escalation_level INT,
    escalation_count INT,
    last_escalation_at DATETIME(6),
    escalation_blocked BIT,
    sla_adjusted_minutes INT,
    previous_agent_id BIGINT,
    escalation_hold_until DATETIME(6),
    escalation_hold_reason VARCHAR(500),
    sla_paused BIT,
    sla_paused_at DATETIME(6),
    sla_pause_reason VARCHAR(500),
    sla_total_paused_minutes BIGINT,
    sla_extended_minutes INT,
    sla_extension_reason VARCHAR(500),
    sla_business_hours_only BIT,
    process_instance_id VARCHAR(255),
    current_task_id VARCHAR(255),
    assigned_at DATETIME(6),
    resolved_at DATETIME(6),
    closed_at DATETIME(6),
    satisfaction_rating INT,
    satisfaction_comment VARCHAR(500),
    resolution_time_minutes BIGINT,
    category VARCHAR(50),
    normalized_category_id BIGINT,
    resolution_summary TEXT,
    resolution_diagnostic TEXT,
    resolution_root_cause TEXT,
    resolution_actions_taken TEXT,
    resolution_next_recommendation TEXT,
    waiting_on VARCHAR(20),
    pending_reason VARCHAR(500),
    manager_review_reason VARCHAR(500),
    resolution_rejected_reason VARCHAR(500),
    last_customer_response_at DATETIME(6),
    alfresco_folder_id VARCHAR(255),
    client_id BIGINT NOT NULL,
    created_by_user_id BIGINT,
    assigned_agent_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_tickets_reference UNIQUE (reference),
    CONSTRAINT fk_tickets_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_tickets_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_assigned_agent FOREIGN KEY (assigned_agent_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_previous_agent FOREIGN KEY (previous_agent_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_category FOREIGN KEY (normalized_category_id) REFERENCES support_categories (id),
    INDEX idx_ticket_reference (reference),
    INDEX idx_ticket_status (status),
    INDEX idx_ticket_priority (priority),
    INDEX idx_ticket_created (created_at),
    INDEX idx_ticket_sla_deadline (sla_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_tags (
    ticket_id BIGINT NOT NULL,
    tag VARCHAR(30),
    CONSTRAINT fk_ticket_tags_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comments (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    content TEXT NOT NULL,
    is_internal BIT,
    is_solution BIT,
    ticket_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id),
    INDEX idx_comment_ticket (ticket_id),
    INDEX idx_comment_author (author_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE attachments (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255),
    file_path VARCHAR(500),
    file_size BIGINT,
    content_type VARCHAR(100),
    alfresco_node_id VARCHAR(255),
    checksum VARCHAR(64),
    description VARCHAR(500),
    ticket_id BIGINT NOT NULL,
    uploaded_by_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_attachments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_attachments_uploader FOREIGN KEY (uploaded_by_id) REFERENCES users (id),
    INDEX idx_attachment_ticket (ticket_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ticket_history (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    action VARCHAR(50) NOT NULL,
    field_name VARCHAR(50),
    old_value VARCHAR(500),
    new_value VARCHAR(500),
    description VARCHAR(500),
    performed_by VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    change_type VARCHAR(20),
    ticket_id BIGINT NOT NULL,
    user_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_ticket_history_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_ticket_history_user FOREIGN KEY (user_id) REFERENCES users (id),
    INDEX idx_history_ticket (ticket_id),
    INDEX idx_history_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notifications (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    title VARCHAR(200) NOT NULL,
    message TEXT,
    type VARCHAR(30),
    icon VARCHAR(50),
    link VARCHAR(500),
    sla_percentage INT,
    action_required BIT,
    suggested_actions VARCHAR(1000),
    recommended_agent VARCHAR(200),
    recommended_agent_id BIGINT,
    is_read BIT,
    read_at DATETIME(6),
    ticket_reference VARCHAR(20),
    user_id BIGINT NOT NULL,
    ticket_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    INDEX idx_notification_user (user_id),
    INDEX idx_notification_read (is_read),
    INDEX idx_notification_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_availability (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    agent_id BIGINT NOT NULL,
    status VARCHAR(15) NOT NULL,
    status_since DATETIME(6),
    status_reason VARCHAR(200),
    max_concurrent_tickets INT,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_availability_agent UNIQUE (agent_id),
    CONSTRAINT fk_agent_availability_user FOREIGN KEY (agent_id) REFERENCES users (id),
    INDEX idx_avail_agent (agent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_shifts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    agent_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME(6) NOT NULL,
    end_time TIME(6) NOT NULL,
    is_on_call BIT,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_shifts_user FOREIGN KEY (agent_id) REFERENCES users (id),
    INDEX idx_shift_agent (agent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agent_skills (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    agent_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    skill_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_skills_user FOREIGN KEY (agent_id) REFERENCES users (id),
    CONSTRAINT fk_agent_skills_category FOREIGN KEY (category_id) REFERENCES support_categories (id),
    INDEX idx_agent_skill_agent (agent_id),
    INDEX idx_agent_skill_type (skill_type),
    INDEX idx_agent_skill_category (category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE escalation_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    ticket_id BIGINT NOT NULL,
    from_level INT NOT NULL,
    to_level INT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    triggered_by VARCHAR(10) NOT NULL,
    from_agent_id BIGINT,
    to_agent_id BIGINT,
    description VARCHAR(500),
    sla_percent_at_escalation FLOAT(53),
    was_blocked BIT,
    PRIMARY KEY (id),
    CONSTRAINT fk_escalation_events_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_escalation_events_from_agent FOREIGN KEY (from_agent_id) REFERENCES users (id),
    CONSTRAINT fk_escalation_events_to_agent FOREIGN KEY (to_agent_id) REFERENCES users (id),
    INDEX idx_esc_event_ticket (ticket_id),
    INDEX idx_esc_event_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE escalation_policies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    client_id BIGINT,
    policy_name VARCHAR(100),
    level1_threshold INT,
    level2_threshold INT,
    level3_delay_minutes INT,
    stuck_assigned_minutes INT,
    max_escalations INT,
    cooldown_minutes INT,
    auto_reassign_enabled BIT,
    notify_client_on_escalation BIT,
    is_active BIT,
    PRIMARY KEY (id),
    CONSTRAINT uk_escalation_policies_client UNIQUE (client_id),
    CONSTRAINT fk_escalation_policies_client FOREIGN KEY (client_id) REFERENCES clients (id),
    INDEX idx_esc_policy_client (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE knowledge_articles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    summary VARCHAR(500),
    category VARCHAR(50),
    views INT,
    helpful_count INT,
    not_helpful_count INT,
    is_published BIT,
    author_id BIGINT,
    source_ticket_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_knowledge_articles_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_knowledge_articles_ticket FOREIGN KEY (source_ticket_id) REFERENCES tickets (id),
    INDEX idx_kb_category (category),
    INDEX idx_kb_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE kb_article_tags (
    article_id BIGINT NOT NULL,
    tag VARCHAR(50),
    CONSTRAINT fk_kb_article_tags_article FOREIGN KEY (article_id) REFERENCES knowledge_articles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE satisfaction_surveys (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT,
    ticket_id BIGINT NOT NULL,
    respondent_id BIGINT,
    rating INT,
    comment VARCHAR(1000),
    response_time_minutes BIGINT,
    was_escalated BIT,
    escalation_level_reached INT,
    survey_sent BIT,
    survey_completed BIT,
    PRIMARY KEY (id),
    CONSTRAINT uk_satisfaction_surveys_ticket UNIQUE (ticket_id),
    CONSTRAINT fk_satisfaction_surveys_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_satisfaction_surveys_respondent FOREIGN KEY (respondent_id) REFERENCES users (id),
    INDEX idx_survey_ticket (ticket_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
