apiVersion: v1
kind: Secret
metadata:
  name: supportflow-secrets
  namespace: supportflow
type: Opaque
stringData:
  DB_USERNAME: supportflow
  DB_PASSWORD: supportflow123
  MYSQL_ROOT_PASSWORD: root
  JWT_SECRET: SupportFlowSecretKey2024VeryLongSecretKeyForJWTTokenGeneration
  ALFRESCO_USERNAME: admin
  ALFRESCO_PASSWORD: admin
