apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql-init-configmap.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-runtime-configmap.yaml
  - default-deny-network-policy.yaml
  - application-network-policy.yaml
  - backend-pdb.yaml
