apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportflow-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mejrioussama/supportflow-frontend:sha-c9f340e3e6e5a70073fe02f0f32769a5fbca1cfa
