apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supportflow
resources:
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - backend-patch.yaml
  - frontend-patch.yaml
